export const POST_THOUGHT_REQUEST = "POST_THOUGHT_REQUEST";
export const POST_THOUGHT_SUCCESS = "POST_THOUGHT_SUCCESS";
export const POST_THOUGHT_FAIL = "POST_THOUGHT_FAIL";

export const GET_ALL_POST_THOUGHT_REQUEST = "GET_ALL_POST_THOUGHT_REQUEST";
export const GET_ALL_POST_THOUGHT_SUCCESS = "POST_THOUGHT_SUCCESS";
export const GET_ALL_POST_THOUGHT_FAIL = "POST_THOUGHT_FAIL";

export const LIKE_POST_THOUGHT_REQUEST = "LIKE_POST_THOUGHT_REQUEST";
export const LIKE_POST_THOUGHT_SUCCESS = "LIKE_POST_THOUGHT_SUCCESS";
export const LIKE_POST_THOUGHT_FAIL = "LIKE_POST_THOUGHT_FAIL";

export const GET_USER_THOT_REQUEST = "GET_USER_THOT_REQUEST";
export const GET_USER_THOT_SUCCESS = "GET_USER_THOT_SUCCESS";
export const GET_USER_THOT_FAIL = "GET_USER_THOT_FAIL";

export const DELETE_USER_THOT_REQUEST = "DELETE_USER_THOT_REQUEST";
export const DELETE_USER_THOT_SUCCESS = "DELETE_USER_THOT_SUCCESS";
export const DELETE_USER_THOT_FAIL = "DELETE_USER_THOT_FAIL";
