export const POST_THOUGHT_REQUEST = "POST_THOUGHT_REQUEST";
export const POST_THOUGHT_SUCCESS = "POST_THOUGHT_SUCCESS";
export const POST_THOUGHT_FAIL = "POST_THOUGHT_FAIL";

export const GET_ALL_POST_THOUGHT_REQUEST = "GET_ALL_POST_THOUGHT_REQUEST";
export const GET_ALL_POST_THOUGHT_SUCCESS = "POST_THOUGHT_SUCCESS";
export const GET_ALL_POST_THOUGHT_FAIL = "POST_THOUGHT_FAIL";
