export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTRATION_VALIDATION = "USER_REGISTRATION_VALIDATION";
export const USER_REGISTRATION_VALIDATION_NAME =
  "USER_REGISTRATION_VALIDATION_NAME";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_IS_LOGGED_REQUEST = "USER_IS_LOGGED_REQUEST";
export const USER_IS_LOGGED_SUCCESS = "USER_IS_LOGGED_SUCCESS";
export const USER_IS_LOGGED_FAIL = "USER_IS_LOGGED_FAIL";
